### ISSUE TITLE
data document

### ISSUE THREAD

**Issue by huynhdoanho** [ajpotts01/eventsim_streaming#21]
Hi, your project is great. Do you have any documents about the data which is generated by eventsim?

**Comment by huynhdoanho** [comment]
oh I just found it in eventsim/confluents-schema, =))

**Comment by ajpotts01** [comment]
G'day, thanks for the message. There's also the [original repo](https://github.com/Interana/eventsim). It has a lot more documentation.

Although eventually we vendored in the version of it from [this repo](https://github.com/viirya/eventsim) as the original didn't build for us anymore and didn't have time to fix it. The version in our repo is edited to add Confluent support. Hope this helps!
